### ISSUE TITLE
New Release - Add v5 for Linux

### ISSUE THREAD

**Issue by mbentley** [mbentley/docker-omada-controller#155]
https://static.tp-link.com/upload/software/2022/202201/20220107/Omada_SDN_Controller_v5.0.29_linux_x64.tar.gz

**Comment by mbentley** [comment]
Images have been built and are up on Docker Hub.  Please give them a test (making sure to take backups if you do upgrade to test) as there are some differences in how the app is run in 5.0.x since it is using springboot.  I think I caught all of the differences from the `install.sh` script but it would be good to get more eyes on it.  I've only done some quick smoke tests on the amd64 and arm64 builds but I assume that the armv7l build works as well.

**Comment by bburan** [comment]
I accidentally updated to this version (I had to restart my docker container and was using the `latest` tag). It's failing to start. I get the following log:
```
Starting omada-controller ... done
Attaching to omada-controller
omada-controller    | INFO: Time zone set to 'Etc/UTC'
omada-controller    | INFO: Setting 'portal.https.port' to 8043 in omada.properties
omada-controller    | INFO: Re-enabling TLS 1.0 & 1.1
omada-controller    | INFO: Starting Omada Controller as user omada
omada-controller    | 01-07-2022 18:08:19.631 INFO [log4j-thread] [] c.t.s.o.c.o.a.b(32): success to load configuration omada.properties
omada-controller    | 01-07-2022 18:08:19.660 INFO [main] [] c.t.s.o.s.OmadaBootstrap(79): going to start local mongod.
omada-controller    | 01-07-2022 18:09:59.729 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Fail to start mongo DB server
omada-controller    | 01-07-2022 18:09:59.730 WARN [main] [] c.t.s.o.s.s.b(145): Fail to start mongo DB server
omada-controller    | 01-07-2022 18:09:59.730 WARN [main] [] c.t.s.o.s.s.a(77): com.tplink.smb.omada.starter.b.a: Fail to start mongo DB server
omada-controller    | com.tplink.smb.omada.starter.b.a: Fail to start mongo DB server
omada-controller    |   at com.tplink.smb.omada.starter.server.b.a(SourceFile:146) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.server.a.e(SourceFile:74) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.d(SourceFile:218) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.q(SourceFile:290) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.a(SourceFile:89) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.e(SourceFile:245) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaLinuxMain.a(SourceFile:84) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaLinuxMain.main(SourceFile:36) [local-starter-5.0.29.jar:5.0.29]
omada-controller    | 01-07-2022 18:11:41.820 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Fail to start mongo DB server
omada-controller    | 01-07-2022 18:11:41.821 WARN [main] [] c.t.s.o.s.s.b(145): Fail to start mongo DB server
omada-controller    | 01-07-2022 18:11:41.821 WARN [main] [] c.t.s.o.s.s.a(77): com.tplink.smb.omada.starter.b.a: Fail to start mongo DB server
omada-controller    | com.tplink.smb.omada.starter.b.a: Fail to start mongo DB server
omada-controller    |   at com.tplink.smb.omada.starter.server.b.a(SourceFile:146) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.server.a.e(SourceFile:74) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.d(SourceFile:218) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.n(SourceFile:211) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.q(SourceFile:293) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.a(SourceFile:89) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.e(SourceFile:245) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaLinuxMain.a(SourceFile:84) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaLinuxMain.main(SourceFile:36) [local-starter-5.0.29.jar:5.0.29]
omada-controller    | 01-07-2022 18:11:43.823 INFO [mongo-check-thread] [] c.t.s.o.s.OmadaBootstrap(315): mongod was shutdown, restarting it
omada-controller    |
omada-controller    |   .   ____          _            __ _ _
omada-controller    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
omada-controller    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
omada-controller    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
omada-controller    |   '  |____| .__|_| |_|_| |_\__, | / / / /
omada-controller    |  =========|_|==============|___/=/_/_/_/
omada-controller    |  :: Spring Boot ::                (v2.4.3)
omada-controller    |
omada-controller    | 01-07-2022 18:12:13.006 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(55): Starting OmadaLinuxMain v5.0.29 using Java 1.8.0_312 on nutshell with PID 1 (/opt/tplink/EAPController/lib/local-starter-5.0.29.jar started by omada in /opt/tplink/EAPController/lib)
omada-controller    | 01-07-2022 18:12:13.024 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(660): No active profile set, falling back to default profiles: default
omada-controller    | 01-07-2022 18:12:23.267 WARN [main] [] o.s.d.c.CustomConversions(260): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
omada-controller    | 01-07-2022 18:12:54.113 WARN [main] [] c.t.s.o.s.a.b(81): Mongo Client connect error while init Jetty.com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
omada-controller    | 01-07-2022 18:13:24.183 ERROR [mongo-check-thread] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Fail to start mongo DB server
omada-controller    | 01-07-2022 18:13:24.184 WARN [mongo-check-thread] [] c.t.s.o.s.s.b(145): Fail to start mongo DB server
omada-controller    | 01-07-2022 18:13:24.185 WARN [mongo-check-thread] [] c.t.s.o.s.s.a(77): com.tplink.smb.omada.starter.b.a: Fail to start mongo DB server
omada-controller    | com.tplink.smb.omada.starter.b.a: Fail to start mongo DB server
omada-controller    |   at com.tplink.smb.omada.starter.server.b.a(SourceFile:146) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.server.a.e(SourceFile:74) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.d(SourceFile:218) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.n(SourceFile:211) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.v(SourceFile:316) ~[local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
omada-controller    | 01-07-2022 18:13:26.723 WARN [main] [] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext(590): Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'portalPictureMongoCrudRepository' defined in com.tplink.smb.omada.portal.port.mongo.omada.portal.file.pic.PortalPictureMongoCrudRepository defined in @EnableMongoRepositories declared on MaintainPortalOmadaRepoConfig: Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
omada-controller    | 01-07-2022 18:13:26.800 ERROR [main] [] o.s.b.SpringApplication(856): Application run failed
omada-controller    | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'portalPictureMongoCrudRepository' defined in com.tplink.smb.omada.portal.port.mongo.omada.portal.file.pic.PortalPictureMongoCrudRepository defined in @EnableMongoRepositories declared on MaintainPortalOmadaRepoConfig: Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:925) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) ~[spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar:2.4.3]
omada-controller    |   at com.tplink.smb.omada.starter.task.SpringBootStartUpTask.execute(SourceFile:31) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.task.c.a(SourceFile:20) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaBootstrap.f(SourceFile:302) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaLinuxMain.a(SourceFile:91) [local-starter-5.0.29.jar:5.0.29]
omada-controller    |   at com.tplink.smb.omada.starter.OmadaLinuxMain.main(SourceFile:36) [local-starter-5.0.29.jar:5.0.29]
omada-controller    | Caused by: org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
omada-controller    |   at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:88) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2881) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:563) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:214) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:156) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:146) ~[spring-data-mongodb-3.1.5.jar:3.1.5]omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:130) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:114) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:54) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:420) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:377) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:406) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:258) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:201) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:87) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:73) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:151) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:125) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:281) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.util.Lazy.getNullable(Lazy.java:230) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:119) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   ... 21 more
omada-controller    | Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
omada-controller    |   at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177) ~[mongodb-driver-core-4.1.1.jar:?]
omada-controller    |   at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:42) ~[mongodb-driver-core-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:135) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:95) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:266) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810) ~[mongodb-driver-sync-4.1.1.jar:?]
omada-controller    |   at org.springframework.data.mongodb.core.DefaultIndexOperations.lambda$ensureIndex$0(DefaultIndexOperations.java:131) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:561) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:214) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.createIndex(MongoPersistentEntityIndexCreator.java:156) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForAndCreateIndexes(MongoPersistentEntityIndexCreator.java:146) ~[spring-data-mongodb-3.1.5.jar:3.1.5]omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.checkForIndexes(MongoPersistentEntityIndexCreator.java:130) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:114) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexCreator.onApplicationEvent(MongoPersistentEntityIndexCreator.java:54) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:420) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:377) ~[spring-context-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:406) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:258) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:201) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:87) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:73) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getEntityInformation(MongoRepositoryFactory.java:151) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.mongodb.repository.support.MongoRepositoryFactory.getTargetRepository(MongoRepositoryFactory.java:125) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:281) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:323) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.util.Lazy.getNullable(Lazy.java:230) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.util.Lazy.get(Lazy.java:114) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:329) ~[spring-data-commons-2.4.5.jar:2.4.5]
omada-controller    |   at org.springframework.data.mongodb.repository.support.MongoRepositoryFactoryBean.afterPropertiesSet(MongoRepositoryFactoryBean.java:119) ~[spring-data-mongodb-3.1.5.jar:3.1.5]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782) ~[spring-beans-5.3.4.jar:5.3.4]
omada-controller    |   ... 21 more
omada-controller    | 01-07-2022 18:13:26.810 ERROR [main] [] c.t.s.o.s.t.SpringBootStartUpTask(37): Cannot start up springboot. reson:Error creating bean with name 'portalPictureMongoCrudRepository' defined in com.tplink.smb.omada.portal.port.mongo.omada.portal.file.pic.PortalPictureMongoCrudRepository defined in @EnableMongoRepositories declared on MaintainPortalOmadaRepoConfig: Invocation of init method failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=127.0.0.1:27217, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
omada-controller    | 01-07-2022 18:13:26.810 INFO [main] [] c.t.s.o.s.t.SpringBootStartUpTask(38): Try to reset default certificate and restart springBoot.
```

**Comment by mbentley** [comment]
Besides switching to a specific tag and not using latest, could you either add the environment variable `-e SHOW_MONGODB_LOGS=true` so that it will show the mongodb logs or grab the logs from `/opt/tplink/EAPController/logs/mongod.log`?  A `docker cp <container-id-or-name>:/opt/tplink/EAPController/logs/mongod.log mongod.log` would do it.

**Comment by bburan** [comment]
@mbentley The logs gave me a clue. There was a permission issue. After fixing it, all is good. Somehow the ownership of one of the files in the docker volume got set to a nonexistent user (likely related to uninstalling/reinstalling docker). Sorry for the trouble! v5 looks great!

**Comment by Vendo232** [comment]
Sorry, just opened a new issue before seeing this. My docker won`t start as well, my log is short

```

INFO: Time zone set to 'Etc/UTC'

INFO: Starting Omada Controller as user omada

Error: Could not find or load main class com.tplink.omada.start.OmadaLinuxMain
```

**Comment by mbentley** [comment]
No problem @Vendo232.  It's probably best to keep issues separate actually as it will keep things cleaner.  Will respond over in https://github.com/mbentley/docker-omada-controller/issues/160
