### ISSUE TITLE
Can't enable data retention when using port 443 for management

### ISSUE THREAD

**Issue by BJD1997** [mbentley/docker-omada-controller#217]
**Describe the bug**
When using port 443 for management I can't turn on data retention under controller settings.
It complains to use port 1024 or higher. So I can't save the setting.
If you change the management port and then change the ports in the docker container the web interface works again.
But when changing it back to 443 using docker the controller seems broken.

**To Reproduce**

1. run controller in docker using ports in configuration below
2. Setup controller like you normally would do
3. Go to settings -> Controller
4. tick the "Collect Clients' History Data" box and save

**Expected behavior**
Save the setting

**How you're launching your container**

```
docker run -d \
  --name omada-controller \
  --restart unless-stopped \
  --sysctl net.ipv4.ip_unprivileged_port_start=0 \
  -p 80:80 \
  -p 443:443 \
  -p 8088:8088 \
  -p 8843:8843 \
  -p 29810:29810/udp \
  -p 29811:29811 \
  -p 29812:29812 \
  -p 29813:29813 \
  -p 29814:29814 \
  -e MANAGE_HTTP_PORT=80 \
  -e MANAGE_HTTPS_PORT=443 \
  -e PGID="508" \
  -e PORTAL_HTTP_PORT=8088 \
  -e PORTAL_HTTPS_PORT=8843 \
  -e PUID="508" \
  -e SHOW_SERVER_LOGS=true \
  -e SHOW_MONGODB_LOGS=false \
  -e SSL_CERT_NAME="tls.crt" \
  -e SSL_KEY_NAME="tls.key" \
  -e TZ=Etc/UTC \
  -v omada-data:/opt/tplink/EAPController/data \
  -v omada-work:/opt/tplink/EAPController/work \
  -v omada-logs:/opt/tplink/EAPController/logs \
  -v omada-certs:/cert \
  mbentley/omada-controller:5.3
```

**Container Logs**

```
INFO: Validating user/group (omada:omada) exists with correct UID/GID (508:508)
INFO: Group (omada) doesn't exist; creating
INFO: User (omada) doesn't exist; creating
INFO: Time zone set to 'Etc/UTC'
INFO: Setting 'manage.http.port' to 80 in omada.properties
INFO: Setting 'manage.https.port' to 443 in omada.properties
WARN: ownership not set correctly on '/opt/tplink/EAPController/work'; setting correct ownership (omada:omada)
INFO: Importing cert from /cert/tls.[key|crt]
INFO: Starting Omada Controller as user omada
07-13-2022 12:50:08.120 INFO [log4j-thread] [] c.t.s.o.c.o.a.b(32): success to load configuration omada.properties
07-13-2022 12:50:08.191 INFO [main] [] c.t.s.o.s.OmadaBootstrap(86): going to start local mongod.
07-13-2022 12:50:11.217 INFO [main] [] c.t.s.o.s.s.b(161): mongodb process id is 71
07-13-2022 12:50:11.220 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Mongo DB server started
07-13-2022 12:50:11.221 INFO [main] [] c.t.s.o.s.s.b(142): Mongo DB server started

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.6)

07-13-2022 12:50:13.640 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(55): Starting OmadaLinuxMain v5.3.1 using Java 1.8.0_312 on 6ff9a6e70f78 with PID 1 (/opt/tplink/EAPController/lib/local-starter-5.3.1.jar started by omada in /opt/tplink/EAPController/lib)
07-13-2022 12:50:13.655 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(640): No active profile set, falling back to 1 default profile: "default"
07-13-2022 12:50:25.494 WARN [main] [] o.s.d.c.CustomConversions(261): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
07-13-2022 12:50:28.974 WARN [main] [] o.s.d.c.CustomConversions(261): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
07-13-2022 12:50:34.221 INFO [main] [] c.t.s.l.c.s.d.CacheLogConsumeHandler(61): log mq consume task is start...
07-13-2022 12:50:34.232 INFO [main] [] c.t.s.o.s.OmadaLinuxMain(61): Started OmadaLinuxMain in 21.649 seconds (JVM running for 27.403)
07-13-2022 12:50:36.179 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(124): upgrade workGroup core thread num is 4, max thread num is 4
07-13-2022 12:50:36.228 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(151): upgradeSendReq workGroup core thread num is 4, max thread num is 4
07-13-2022 12:50:36.537 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(97): manager workGroup core thread  num is 16, max thread num is 16
07-13-2022 12:50:37.971 INFO [main] [] c.t.s.o.m.d.d.m.d.a.c.ApBatchGroupConfig(36): apBatchGroup thread size is 5, queue size is 1500
07-13-2022 12:50:38.280 INFO [main] [] c.t.s.o.m.c.d.m.s.w.s.c.WirelessGroupConfig(37): ssidWorkerGroup thread size is 5, queue size is 1500
07-13-2022 12:50:39.564 INFO [main] [] c.t.s.e.s.c.c(158): start schedule remove expire device... period = 10
07-13-2022 12:50:39.574 INFO [main] [] c.t.s.e.s.c.c(145): update rateLimiterCache, permitsPerSecond = 5.0
07-13-2022 12:50:39.615 INFO [main] [] c.t.s.o.m.d.d.m.m.c.DeviceMsgConfig(38): setMsgThreadPool thread size is 4, queue size is 10000
07-13-2022 12:50:39.976 INFO [main] [] c.t.s.o.s.d.a(78): Db unchanged. No need to compatible or init data.
07-13-2022 12:50:40.110 INFO [main] [] c.t.s.o.s.t.OmadacInitTask(149): succeed get default omadac OmadacVO(id=34e1a567cdb6364a4192adf8f1370002, name=davidshosting)
07-13-2022 12:50:40.241 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(70): adopt workGroup core thread num is 8, max thread num is8
07-13-2022 12:50:40.961 INFO [main] [] c.t.s.o.m.d.p.t.TransportConfiguration(43): discovery workGroup core thread num is 2, max thread num is 10
07-13-2022 12:50:41.282 INFO [main] [] c.t.s.o.m.l.p.e.LicenseEventCenterProperties(36): licenseManagerTopic: omada.cloud.license.prd.topics
07-13-2022 12:50:41.429 INFO [main] [] c.t.s.o.d.g.c.d.ThreadConfiguration(48): device-gateway datatrack workGroup core thread  num is 4, max thread num is 4
07-13-2022 12:50:41.717 INFO [main] [] c.t.s.o.p.p.r.a.b(125): init nioEventLoopGroup
07-13-2022 12:50:43.531 INFO [main] [] c.t.s.o.d.g.c.d.ThreadConfiguration(69): device-gateway datatrack time task workGroup core thread  num is 4, max thread num is 4
07-13-2022 12:50:44.046 INFO [main] [] c.t.s.o.p.b.a.c(72): DisconnectRequestServer start
07-13-2022 12:50:44.642 INFO [main] [] c.t.s.o.m.c.d.m.s.d.f(197): Add Dst Schedule false for Site 62cea573d78794263c9445ca on 1664672400000.
07-13-2022 12:50:44.972 INFO [main] [] c.t.s.o.d.g.a(124): discovery Port is 29810.
07-13-2022 12:50:44.973 INFO [main] [] c.t.s.o.d.g.a(125): manage    port v1 is 29811.
07-13-2022 12:50:44.973 INFO [main] [] c.t.s.o.d.g.a(126): manage    port v2 is 29814.
07-13-2022 12:50:44.974 INFO [main] [] c.t.s.o.d.g.a(127): adopt     port v1 is 29812.
07-13-2022 12:50:44.980 INFO [main] [] c.t.s.o.d.g.a(128): upgrade   port is 29813.
07-13-2022 12:50:45.048 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyUdpServer bind /0.0.0.0:29810, export localhost/127.0.0.1:29810
07-13-2022 12:50:45.061 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29812 global traffic shaping, writeLimit: 477364224, readLimit: 0, checkInterval: 1000, max wait time: 15000
07-13-2022 12:50:45.079 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29812, export localhost/127.0.0.1:29812
07-13-2022 12:50:45.081 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29811 global traffic shaping, writeLimit: 477364224, readLimit: 0, checkInterval: 1000, max wait time: 15000
07-13-2022 12:50:45.091 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29811, export localhost/127.0.0.1:29811
07-13-2022 12:50:45.099 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29813 global traffic shaping, writeLimit: 477364224, readLimit: 0, checkInterval: 1000, max wait time: 15000
07-13-2022 12:50:45.106 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29813, export localhost/127.0.0.1:29813
07-13-2022 12:50:45.111 INFO [main] [] c.t.s.e.t.n.NettyTcpServer(119): TCP server /0.0.0.0:29814 global traffic shaping, writeLimit: 477364224, readLimit: 0, checkInterval: 1000, max wait time: 15000
07-13-2022 12:50:45.118 INFO [main] [] c.t.s.e.t.a.t.AbstractServer(53): Start NettyTcpServer bind /0.0.0.0:29814, export localhost/127.0.0.1:29814
07-13-2022 12:50:45.120 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Device connector server started.
07-13-2022 12:50:45.121 ERROR [main] [] c.t.s.f.c.FacadeUtils(68): facadeMsgEnable is not enable, msg: Omada Controller started
07-13-2022 12:50:45.124 INFO [main] [] c.t.s.o.s.t.SuccessExitTask(23): Omada Controller started
07-13-2022 12:50:46.621 INFO [discovery-work-group-0] [] c.t.s.o.m.d.d.m.a.a(332): MANAGED_BY_OWN Device 54-AF-97-72-AE-92 on omadac 34e1a567cdb6364a4192adf8f1370002 is discoveried.
07-13-2022 12:50:50.238 INFO [Thread-5] [] c.t.e.c.c.CloudClient(100): CloudClient is started.
07-13-2022 12:50:50.238 INFO [Thread-5] [] c.t.e.c.c.CloudClient(110): Connect SEF server automatically.
07-13-2022 12:50:51.317 INFO [Thread-5] [] c.t.e.c.c.n(194): The result of connection is true, service host is n-device-omada.tplinkcloud.com, port is 443.
07-13-2022 12:50:51.319 INFO [Thread-5] [] c.t.e.c.c.CloudClient(114): Close connection to SEF server.
07-13-2022 12:50:51.326 INFO [Thread-8] [] c.t.e.c.c.n(403): javax.net.ssl.SSLException: Socket closed
javax.net.ssl.SSLException: Socket closed
	at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:1.8.0_312]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:1.8.0_312]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:1.8.0_312]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1563) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.access$400(SSLSocketImpl.java:73) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973) ~[?:1.8.0_312]
	at com.tplink.eap.cloudsdk.client.p.a(SourceFile:120) ~[cloudsdk-1.0.12.jar:?]
	at com.tplink.eap.cloudsdk.client.o.run(SourceFile:397) [cloudsdk-1.0.12.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_312]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_312]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_312]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:464) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1341) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:73) ~[?:1.8.0_312]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:957) ~[?:1.8.0_312]
	... 3 more
07-13-2022 12:50:51.339 INFO [Thread-8] [] c.t.e.c.c.n(407): ssl recv thread is stopped.
07-13-2022 12:50:51.369 INFO [Thread-5] [] c.t.e.c.c.CloudClient(128): Connect service server automatically, ConnectionType is PERSISTENT_CONNECTION.
07-13-2022 12:50:51.395 INFO [Thread-5] [] c.t.e.c.c.q(196): set connection status: CONNECTING
07-13-2022 12:50:51.829 INFO [adopt-work-group-4] [] c.t.s.o.m.d.d.m.a.c(168): send empty setting to OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-92)
07-13-2022 12:50:51.841 INFO [Thread-5] [] c.t.e.c.c.q(196): set connection status: CONNECTED
07-13-2022 12:50:51.841 INFO [Thread-5] [] c.t.e.c.c.q(373): The result of connection is true.
07-13-2022 12:50:51.842 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:50:51.949 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":2}
07-13-2022 12:50:52.082 INFO [manage-work-group-1] [] c.t.s.o.m.d.p.t.c(129): Device 54-AF-97-72-AE-92 OmadacId(34e1a567cdb6364a4192adf8f1370002) changed to status CONNECTED, which don't need to handle.
07-13-2022 12:50:52.126 INFO [manage-work-group-2] [] c.t.s.o.m.d.d.m.i.a(86): got first inform of OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-92)
07-13-2022 12:50:52.274 INFO [manage-work-group-3] [] c.t.s.o.m.d.d.m.i.d(194): first inform send same version config to OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-92)
07-13-2022 12:50:52.478 INFO [manage-work-group-4] [] c.t.s.o.m.d.d.m.d.a.N(100): syncConfigurationForSameVersion to OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-92), result:SendDeviceMsgResult(success=true, deviceResponse=com.tplink.smb.omada.device.manage.message.body.manage.BaseConfigRespBody@1e6edde)
07-13-2022 12:51:02.190 WARN [manage-work-group-5] [] c.t.s.o.m.d.d.m.i.a.UpdateApImageCommonInfoService(112): omadacId:OmadacId(34e1a567cdb6364a4192adf8f1370002), siteId:SiteId(62cea573d78794263c9445ca), deviceMac:54-AF-97-72-AE-92, apImage wlanId is null, need query database
07-13-2022 12:51:04.121 INFO [discovery-work-group-1] [] c.t.s.o.m.d.d.m.a.a(332): MANAGED_BY_OWN Device 54-AF-97-72-AE-FE on omadac 34e1a567cdb6364a4192adf8f1370002 is discoveried.
07-13-2022 12:51:07.414 WARN [https-jsse-nio-8843-exec-6] [] o.s.d.c.CustomConversions(261): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
07-13-2022 12:51:07.471 WARN [https-jsse-nio-8843-exec-6] [] o.s.d.c.CustomConversions(261): Registering converter from class java.time.LocalDateTime to class org.joda.time.LocalDateTime as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
07-13-2022 12:51:08.600 INFO [adopt-work-group-3] [] c.t.s.o.m.d.d.m.a.c(168): send empty setting to OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-FE)
07-13-2022 12:51:08.736 INFO [manage-work-group-9] [] c.t.s.o.m.d.p.t.c(129): Device 54-AF-97-72-AE-FE OmadacId(34e1a567cdb6364a4192adf8f1370002) changed to status CONNECTED, which don't need to handle.
07-13-2022 12:51:08.791 INFO [manage-work-group-10] [] c.t.s.o.m.d.d.m.i.a(86): got first inform of OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-FE)
07-13-2022 12:51:08.809 INFO [manage-work-group-11] [] c.t.s.o.m.d.d.m.i.d(194): first inform send same version config to OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-FE)
07-13-2022 12:51:08.867 INFO [manage-work-group-12] [] c.t.s.o.m.d.d.m.d.a.N(100): syncConfigurationForSameVersion to OmadacId(34e1a567cdb6364a4192adf8f1370002) DeviceMac(54-AF-97-72-AE-FE), result:SendDeviceMsgResult(success=true, deviceResponse=com.tplink.smb.omada.device.manage.message.body.manage.BaseConfigRespBody@1e6edde)
07-13-2022 12:51:19.637 WARN [manage-work-group-15] [] c.t.s.o.m.d.d.m.i.a.UpdateApImageCommonInfoService(112): omadacId:OmadacId(34e1a567cdb6364a4192adf8f1370002), siteId:SiteId(62cea573d78794263c9445ca), deviceMac:54-AF-97-72-AE-FE, apImage wlanId is null, need query database
07-13-2022 12:51:30.797 INFO [check-update-work-group-0] [] c.t.s.o.m.b.e(153): Start sync Cloud Users OmadacId(34e1a567cdb6364a4192adf8f1370002).
07-13-2022 12:51:30.938 INFO [check-update-work-group-0] [] c.t.s.o.m.b.e(118): Start checking last firmwares of managed devices.
07-13-2022 12:51:30.951 INFO [check-update-work-group-0] [] c.t.s.o.m.b.b(95): Checking Device Last Firmware...
07-13-2022 12:51:31.942 INFO [check-update-work-group-0] [] c.t.s.o.m.b.e(128): Checking last firmwares of managed devices succeed.
07-13-2022 12:51:51.950 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:51:52.051 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":3}
07-13-2022 12:51:53.775 INFO [log-device-status-push-info-event-pool-1] [] c.t.s.o.l.c.b(50): Start pushing new connected devices.
07-13-2022 12:52:52.052 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:52:52.153 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":4}
07-13-2022 12:53:52.154 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:53:52.255 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":5}
07-13-2022 12:54:52.256 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:54:52.358 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":6}
07-13-2022 12:55:52.358 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:55:52.460 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":7}
07-13-2022 12:56:52.460 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:56:52.562 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":8}
07-13-2022 12:57:52.563 INFO [Thread-11] [] c.t.e.c.c.q(891): send tp cloud heartbeat
07-13-2022 12:57:52.664 INFO [Thread-11] [] c.t.e.c.c.q(893): heartbeat reponse: {"error_code":0,"id":9}
```

**Comment by mbentley** [comment]
Interesting.  I will have to see if I can reproduce this.  I use ports 80/443 and I have `Collect Clients' History Data` enabled in `History Data Retention`.  I know that at one point, I was using the default ports so I may have had this setting already set before switching the ports over to 80/443 so I will have to setup a new controller to test when I have the chance.

**Comment by BJD1997** [comment]
Thanks for your reply. Let me know if I can help :)

**Comment by mbentley** [comment]
Yeah, I can definitely reproduce this.  So I can see it's the software blocking the settings from being saved.  Not sure if they added a check to validate the port range at some point; I'll have to check previous versions to see if they had a port check in the UI as well.

**Comment by mbentley** [comment]
OK, so after checking version 4.1 to the latest, they removed 443 from the list of allowed ports in 5.1:

5.1
<img width="663" alt="screenshot 2022-07-14 at 6 06 56 AM" src="https://user-images.githubusercontent.com/414445/178958363-3c5a9c7a-fa05-4b81-81b9-37e99bda5dbd.png">

The best I can do is file an issue on the forums to see if they can add it back, remove the restriction, or just do a proper check to see if they can bind to privileged ports.

**Comment by BJD1997** [comment]
So as a workaround it would be enough to setup the controller on a older version and after that upgrade to the latest version?

**Comment by BJD1997** [comment]
Also another quick question (unrelated to this). Since you have some experience packaging docker containers (of existing applications). Do you have a good resource for me to try and build my own docker containers?

**Comment by mbentley** [comment]
So a better workaround is by using the API.  Below is a script that will utilize `curl` and `jq` which you need to install to enable the data retention.  If you need a linux CLI where you can get those tools, you can just run this container which has both and will drop you in a shell:
```
docker run -it --rm mbentley/swissarmy
```

The last command that does a `PATCH` will set the retention.  You need to adjust the value (it appears to be in days) from 180 to whatever you want and `clientsDataEnable":true` will enable it:

```
#!/bin/bash

# set variables
OMADA_URL="https://localhost:443"
USERNAME="admin"
PASSWORD="password"

# get controller id from the API
CONTROLLER_ID="$(curl -sk "${OMADA_URL}/api/info" | jq -r .result.omadacId)"

# login, get token, set & use cookies
TOKEN="$(curl -sk -X POST -c "/tmp/omada-cookies.txt" -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/login" -d '{"username": "'"${USERNAME}"'", "password": "'"${PASSWORD}"'"}' | jq -r .result.token)"

# set data retention (180 = 6mo)
curl -sk -X PATCH -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" -H "Csrf-Token: ${TOKEN}" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/controller/history?token=${TOKEN}" -d '{"retention":180,"clientsDataEnable":true}'
```

When you run this, you should see output like:

```
$ bash test.sh
{
  "errorCode": 0,
  "msg": "Success.",
  "result": {
    "login": true
  }
}
{"errorCode":0,"msg":"Success."}
```

And then you should be able to see in the UI that the value has changed.

**Comment by mbentley** [comment]
> Also another quick question (unrelated to this). Since you have some experience packaging docker containers (of existing applications). Do you have a good resource for me to try and build my own docker containers?

Will have to get back to you on that.  Been a looooong time since I've gone down that route as I started Dockerizing apps in 2014 and am mostly self taught and learning through others while I was working at Docker.

**Comment by mbentley** [comment]
I was wondering if it was possible to set the port to 443 from the Omada Controller API but it looks like they perform the validation from the API, not just the UI:

```
#!/bin/bash

# set variables
OMADA_URL="https://localhost:8043"
USERNAME="admin"
PASSWORD="password"

# get controller id from the API
CONTROLLER_ID="$(curl -sk "${OMADA_URL}/api/info" | jq -r .result.omadacId)"

# login, get token, set & use cookies
TOKEN="$(curl -sk -X POST -c "/tmp/omada-cookies.txt" -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/login" -d '{"username": "'"${USERNAME}"'", "password": "'"${PASSWORD}"'"}' | jq -r .result.token)"

# change controller port
curl -sk -X PATCH -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" -H "Csrf-Token: ${TOKEN}" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/controller/setting?token=${TOKEN}" -d '{"webPort":{"manageHttpsPort":443}}'
```

Then to run it:

```
$ bash test.sh
{"errorCode":-30033,"msg":"The HTTP or HTTPS port is out of range."}
```

**Comment by BJD1997** [comment]
> So a better workaround is by using the API. Below is a script that will utilize `curl` and `jq` which you need to install to enable the data retention. If you need a linux CLI where you can get those tools, you can just run this container which has both and will drop you in a shell:
> 
> ```
> docker run -it --rm mbentley/swissarmy
> ```
> 
> The last command that does a `PATCH` will set the retention. You need to adjust the value (it appears to be in days) from 180 to whatever you want and `clientsDataEnable":true` will enable it:
> 
> ```
> #!/bin/bash
> 
> # set variables
> OMADA_URL="https://localhost:443"
> USERNAME="admin"
> PASSWORD="password"
> 
> # get controller id from the API
> CONTROLLER_ID="$(curl -sk "${OMADA_URL}/api/info" | jq -r .result.omadacId)"
> 
> # login, get token, set & use cookies
> TOKEN="$(curl -sk -X POST -c "/tmp/omada-cookies.txt" -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/login" -d '{"username": "'"${USERNAME}"'", "password": "'"${PASSWORD}"'"}' | jq -r .result.token)"
> 
> # set data retention (180 = 6mo)
> curl -sk -X PATCH -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" -H "Csrf-Token: ${TOKEN}" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/controller/history?token=${TOKEN}" -d '{"retention":180,"clientsDataEnable":true}'
> ```
> 
> When you run this, you should see output like:
> 
> ```
> $ bash test.sh
> {"errorCode":0,"msg":"Success."}
> ```
> 
> And then you should be able to see in the UI that the value has changed.

I've turnede the data rentention back on this way and works perfectly!

**Comment by mbentley** [comment]
Awesome, thanks for the follow up.  I hope that I can still convince them to remove the restriction in the API in the forum post.  I understand why they did it since it could leave people with a controller that is unable to start with no easy way to revert the port but it stinks for those who know how to work around it.

**Comment by mbentley** [comment]
Looks like a permanent fix will be coming [according to Fae](https://community.tp-link.com/en/business/forum/topic/570870?replyId=1116564):
> Thanks so much for your valuable feedback! I've shared the situation to the R&D team for further investigation and evaluation. It's confirmed that Omada Controller 5.5 (Linux) will add the support of port 443 back, additional note for using port 443 will be added. Cheers!

**Comment by BJD1997** [comment]
That's great news! For me this issue is solved :) Thanks for the help!

**Comment by BJD1997** [comment]
I've updated my controller to 5.5.6 and port 443 is fixed but now it's bugging me about port 80 usage....

**Comment by mbentley** [comment]
Just curious - which ports do you have configured for port 80?  Just `MANAGE_HTTP_PORT`?  If so, I believe that one should be fairly low value to actually be port 80 since I am pretty confident that it only handles a redirect from http to https and nothing else.

**Comment by BJD1997** [comment]
Yes have port 80 configured. But this now shows up in the interface as before it wasn't shown. So it fails exactly the same as 443 dit before.

**Comment by mbentley** [comment]
Oh geez, I didn't make that connection.  I'll see if they can do the same for port 80 then 🤦

**Comment by mbentley** [comment]
Re-opening for now.

**Comment by mbentley** [comment]
Port 80 is still a problem.  Bumping back up in the forums thread.

**Comment by BJD1997** [comment]
Just updated form 5.6.3 to 5.7.4 and looked at the settings page. The issue with port 80 has been resolved now.
I don't know which release it was that fixed it but it's solved now :D

**Comment by rickdgray** [comment]
For anyone landing here with a broken omada install after fussing with port numbers, I was able to fix my install using [this guide](https://www.tp-link.com/us/support/faq/3429/).

**Comment by mbentley** [comment]
Oh that’s fantastic. I didn’t know about the override option!

**Comment by BJD1997** [comment]
Upgraded to the 5.12 release and tested again. Issue is resolved now.
