### ISSUE TITLE
[Bug]: Update to 5.9.31 Breaks Controller

### ISSUE THREAD

**Issue by johnthomas00** [mbentley/docker-omada-controller#365]
### Controller Version

v5.9.31

### Describe the Bug

Thanks for publishing this, super helpful.

Update to 5.9.31 results in the controller not working.  All prior updates have gone great.  I did not change anything. 

In the GUI, I get a "General Error" popup and "No entry in the table" in the site list, but the GUI is up.  Obviously cannot click onto site.  The Device tab shows my access points with "Adopting" status.  They are only EAP245(US) v3.0 | 5.0.6.

### Expected Behavior

No errors and site to load.

### Steps to Reproduce

Launch GUI

### How You're Launching the Container

```plain
Portainer via the following.
version: "3.1"

services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:5.9
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    network_mode: host
    environment:
      - PUID=508
      - PGID=508
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      - PORT_ADOPT_V1=29812
      - PORT_UPGRADE_V1=29813
      - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      - SSL_CERT_NAME=tls.crt
      - SSL_KEY_NAME=tls.key
      - TZ=America/Los_Angeles
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  omada-data:
  omada-logs:
```

### Container Logs

```plain
11-03-2023 07:16:06.730 WARN [server-comm-pool-10] [] c.t.s.e.s.c.c(): get device adopt info for REDACTED error when handle new pre connect, exception: 
java.lang.NullPointerException: username is marked non-null but is null
        at com.tplink.smb.omada.manager.configuration.domain.model.site.b.b.a.a.<init>(SourceFile:27) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.configuration.domain.model.site.b.b.a.a$b.d(SourceFile:27) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.port.mongo.configuration.site.component.common.f.a(SourceFile:34) ~[manager-port-mongo-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.port.mongo.configuration.site.component.common.d.a(SourceFile:55) ~[manager-port-mongo-5.9.31.jar:5.9.31]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at com.tplink.smb.omada.manager.port.mongo.configuration.site.component.common.c.a(SourceFile:48) ~[manager-port-mongo-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.configuration.domain.model.site.b.b.g.a(SourceFile:31) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.device.port.transport.a.a(SourceFile:207) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.component.lock.api.AbstractReadWriteLockService.doWithTryLockRead(AbstractReadWriteLockService.java:62) ~[solution-components-lock-api-1.1.4.jar:1.1.4]
        at com.tplink.smb.omada.lock.a.b.a(SourceFile:49) ~[omada-lock-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.lock.a.b.a(SourceFile:67) ~[omada-lock-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.device.port.transport.a.a(SourceFile:205) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.device.port.transport.a.a(SourceFile:188) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.device.port.transport.a.a(SourceFile:139) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.omada.manager.device.port.transport.a.getDeviceAdoptInfoAsync(SourceFile:113) ~[manager-core-5.9.31.jar:5.9.31]
        at com.tplink.smb.ecsp.server.context.c.a(SourceFile:496) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.context.helper.EcspV2DeviceContextHelper.updateV2PreConnectDeviceContext(SourceFile:153) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.context.helper.EcspV2DeviceContextHelper.updateV2PreConnectDeviceContext(SourceFile:131) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.context.c.updateV2PreConnectDeviceContext(SourceFile:697) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.a.b.e.a(SourceFile:85) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.a.b.a(SourceFile:59) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.c.n.a(SourceFile:109) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at com.tplink.smb.ecsp.server.c.n.b(SourceFile:90) ~[ecsp-server-core-1.1.80.jar:1.1.80]
        at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:44) ~[micrometer-core-1.8.4.jar:1.8.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### MongoDB Logs

```plain
2023-11-03T07:00:20.477-0700 I CONTROL  [main] ***** SERVER RESTARTED *****
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] MongoDB starting : pid=172 port=27217 dbpath=../data/db 64-bit host=docker01
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] db version v3.6.8
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] git version: 8e540c0b6db93ce994cc548f000900bdc740f80a
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] allocator: tcmalloc
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] modules: none
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] build environment:
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten]     distarch: x86_64
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten]     target_arch: x86_64
2023-11-03T07:00:20.484-0700 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27217 }, processManagement: { pidFilePath: "../data/mongo.pid" }, storage: { dbPath: "../data/db", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: "../logs/mongod.log" } }
2023-11-03T07:00:20.485-0700 I -        [initandlisten] Detected data files in ../data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2023-11-03T07:00:20.485-0700 I STORAGE  [initandlisten] 
2023-11-03T07:00:20.485-0700 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2023-11-03T07:00:20.485-0700 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2023-11-03T07:00:20.485-0700 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7483M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2023-11-03T07:00:21.339-0700 I STORAGE  [initandlisten] WiredTiger message [1699020021:339211][172:0x7f0fdd61aac0], txn-recover: Main recovery loop: starting at 112/412800
2023-11-03T07:00:21.444-0700 I STORAGE  [initandlisten] WiredTiger message [1699020021:444127][172:0x7f0fdd61aac0], txn-recover: Recovering log 112 through 113
2023-11-03T07:00:21.504-0700 I STORAGE  [initandlisten] WiredTiger message [1699020021:504559][172:0x7f0fdd61aac0], txn-recover: Recovering log 113 through 113
2023-11-03T07:00:21.575-0700 I STORAGE  [initandlisten] WiredTiger message [1699020021:575581][172:0x7f0fdd61aac0], txn-recover: Set global recovery timestamp: 0
2023-11-03T07:00:21.855-0700 I CONTROL  [initandlisten] 
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] 
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] 
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2023-11-03T07:00:21.856-0700 I CONTROL  [initandlisten] 
2023-11-03T07:00:23.361-0700 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '../data/db/diagnostic.data'
2023-11-03T07:00:23.364-0700 I NETWORK  [initandlisten] waiting for connections on port 27217
2023-11-03T07:00:23.931-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:55450 #1 (1 connection now open)
2023-11-03T07:00:23.931-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:55448 #2 (2 connections now open)
2023-11-03T07:00:23.943-0700 I NETWORK  [conn1] received client metadata from 127.0.0.1:55450 conn1: { driver: { name: "mongo-java-driver|sync", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:23.943-0700 I NETWORK  [conn2] received client metadata from 127.0.0.1:55448 conn2: { driver: { name: "mongo-java-driver|sync", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:24.012-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:55460 #3 (3 connections now open)
2023-11-03T07:00:24.013-0700 I NETWORK  [conn3] received client metadata from 127.0.0.1:55460 conn3: { driver: { name: "mongo-java-driver|sync", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:24.047-0700 I NETWORK  [conn3] end connection 127.0.0.1:55460 (2 connections now open)
2023-11-03T07:00:24.048-0700 I NETWORK  [conn1] end connection 127.0.0.1:55450 (1 connection now open)
2023-11-03T07:00:24.048-0700 I NETWORK  [conn2] end connection 127.0.0.1:55448 (0 connections now open)
2023-11-03T07:00:24.084-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:55476 #4 (1 connection now open)
2023-11-03T07:00:24.085-0700 I NETWORK  [conn4] received client metadata from 127.0.0.1:55476 conn4: { driver: { name: "mongo-java-driver|sync", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:24.085-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:55480 #5 (2 connections now open)
2023-11-03T07:00:24.086-0700 I NETWORK  [conn5] received client metadata from 127.0.0.1:55480 conn5: { driver: { name: "mongo-java-driver|sync", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:24.089-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:55484 #6 (3 connections now open)
2023-11-03T07:00:24.090-0700 I NETWORK  [conn6] received client metadata from 127.0.0.1:55484 conn6: { driver: { name: "mongo-java-driver|sync", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:24.104-0700 I NETWORK  [conn6] end connection 127.0.0.1:55484 (2 connections now open)
2023-11-03T07:00:24.104-0700 I NETWORK  [conn4] end connection 127.0.0.1:55476 (1 connection now open)
2023-11-03T07:00:24.104-0700 I NETWORK  [conn5] end connection 127.0.0.1:55480 (0 connections now open)
2023-11-03T07:00:32.734-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:59004 #7 (1 connection now open)
2023-11-03T07:00:32.734-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:59020 #8 (2 connections now open)
2023-11-03T07:00:32.735-0700 I NETWORK  [conn8] received client metadata from 127.0.0.1:59020 conn8: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:32.735-0700 I NETWORK  [conn7] received client metadata from 127.0.0.1:59004 conn7: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:34.685-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:59024 #9 (3 connections now open)
2023-11-03T07:00:34.686-0700 I NETWORK  [conn9] received client metadata from 127.0.0.1:59024 conn9: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:00:45.461-0700 I COMMAND  [conn9] CMD: drop omada.constant
2023-11-03T07:00:54.246-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:36454 #10 (4 connections now open)
2023-11-03T07:00:54.246-0700 I NETWORK  [conn10] received client metadata from 127.0.0.1:36454 conn10: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:01:20.621-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:43434 #11 (5 connections now open)
2023-11-03T07:01:20.622-0700 I NETWORK  [conn11] received client metadata from 127.0.0.1:43434 conn11: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:08:50.614-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:53900 #12 (6 connections now open)
2023-11-03T07:08:50.615-0700 I NETWORK  [conn12] received client metadata from 127.0.0.1:53900 conn12: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
2023-11-03T07:11:39.124-0700 I NETWORK  [listener] connection accepted from 127.0.0.1:59200 #13 (7 connections now open)
2023-11-03T07:11:39.125-0700 I NETWORK  [conn13] received client metadata from 127.0.0.1:59200 conn13: { driver: { name: "mongo-java-driver|sync|spring-boot", version: "4.4.2" }, os: { type: "Linux", name: "Linux", architecture: "amd64", version: "6.1.0-13-amd64" }, platform: "Java/Private Build/17.0.8.1+1-Ubuntu-0ubuntu120.04" }
```

### Additional Context

What else would be helpful.

Thanks again for the handy docker solution.

**Comment by djak250** [comment]
I'm seeing this happening on latest.

**Comment by johnpierson** [comment]
I am also seeing this.

**Comment by mbentley** [comment]
Looking into this right now.

**Comment by johnpierson** [comment]
Thanks so much. Let me know if you need anything from me.

I am running in Docker on a Synology NAS with watchtower updates enabled.

**Comment by mbentley** [comment]
All good - I know what the issue is; will have a fix out shortly.

**Comment by mbentley** [comment]
A temporary workaround until the new builds can process is to add an environment variable to the container with the following:

`-e EAP_MONGOD_URI="mongodb://127.0.0.1:27217/omada"`

**Comment by johnpierson** [comment]
The environment variable fixed it for now! Thanks a bunch @mbentley! Really appreciate it.

**Comment by mbentley** [comment]
You bet.  Sorry about that - I rushed a PR for an experimental externalized MongoDB where I forgot to set the default value back to it's original 🤦

**Comment by johnpierson** [comment]
No worries! It happens. The more significant issue was the darn controller given no real info. lol 

`"General Error"` 😬 

Thanks again and Have a great weekend!
