### ISSUE TITLE
Certificate does not mount correctly

### ISSUE THREAD

**Issue by ruslanguns** [mbentley/docker-omada-controller#74]
Before everything, thanks for supporting this repository, you are doing a great job.

The container is not reading the `cert/tls.key` and `cert/tls.crt` it is correctly setup and is right in the / path from the container. But my guess is that it isn't configured correctly to know that this path has the certificates.

In this image you will see my configuration, it is pretty much the same as your command, I use docker-compose for confort.

![image](https://user-images.githubusercontent.com/19806968/100673168-e7905080-335a-11eb-8718-a661bcb73224.png)
 
And in this another image you will see that I did `docker exec` to get inside the container, I have printed the tls.key, as you can see it is there. 
<removed image>
 
But at the end of the day, omada is just getting the self signed certificate and is ignoring the mine.
![image](https://user-images.githubusercontent.com/19806968/100673415-52418c00-335b-11eb-8db7-e310b722d183.png)

Please let me know if you can give me some clues for fixing it, I am having issues with Apple hotspot.

**Comment by mbentley** [comment]
What do the container logs show?  At the beginning, it should try to add the cert to the JKS.

**Comment by mbentley** [comment]
I removed the image that had the private key in it.  Could you also provide the output of the following command?:

```
openssl x509 -in tls.crt -text -noout
```

**Comment by ruslanguns** [comment]
So sorry for the delay, I am here now! 

## This is all the outputs when is created: 
```bash
Creating omada-controller ... done
Attaching to omada-controller
omada-controller | INFO: Time zone set to 'Etc/UTC'
omada-controller | INFO: Starting Omada Controller as user omada
omada-controller | 2020-12-01 18:45:26 [log4j-thread] [INFO]-[SourceFile:29] - success to load configuration omada.properties
omada-controller | 2020-12-01 18:45:27 [main] [INFO]-[SourceFile:89] - going to start local mongod.
omada-controller | 2020-12-01 18:45:29 [main] [INFO]-[SourceFile:167] - mongodb process id is 29
omada-controller | 2020-12-01 18:45:29 [main] [INFO]-[SourceFile:148] - Mongo DB server started
omada-controller | 2020-12-01 18:45:31 [main] [WARN]-[AbstractConnector.java:205] - Acceptors should be <= availableProcessors: ServerConnector@55de24cc{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
omada-controller | 2020-12-01 18:45:31 [main] [WARN]-[AbstractConnector.java:205] - Acceptors should be <= availableProcessors: ServerConnector@7dfb0c0f{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
omada-controller | 2020-12-01 18:46:02 [main] [INFO]-[SourceFile:35] - monitor context initialing...
omada-controller | 2020-12-01 18:46:06 [main] [INFO]-[SourceFile:290] - restart all customize tasks.
omada-controller | 2020-12-01 18:46:09 [main] [INFO]-[SourceFile:126] - no need to compatible db.
omada-controller | 2020-12-01 18:46:09 [main] [INFO]-[SourceFile:20] - Omada Controller started
omada-controller | 2020-12-01 18:46:10 [device-discovery-server] [INFO]-[SourceFile:54] - Start device discovery server
omada-controller | 2020-12-01 18:46:10 [device-manage-server] [INFO]-[SourceFile:111] - Start device manage server
omada-controller | 2020-12-01 18:46:10 [device-adopt-server] [INFO]-[SourceFile:82] - Start device adopt server
omada-controller | 2020-12-01 18:46:12 [Thread-16] [INFO]-[SourceFile:100] - CloudClient is started.
omada-controller | 2020-12-01 18:46:12 [Thread-16] [INFO]-[SourceFile:110] - Connect SEF server automatically.
omada-controller | 2020-12-01 18:46:12 [comm-pool-3] [INFO]-[SourceFile:84] - Starting PF module.
omada-controller | 2020-12-01 18:46:12 [comm-pool-3] [INFO]-[SourceFile:146] - Starting SCMP Server.
omada-controller | 2020-12-01 18:46:12 [comm-pool-3] [INFO]-[SourceFile:120] - Cloud service is started.
omada-controller | 2020-12-01 18:46:13 [Thread-16] [INFO]-[SourceFile:194] - The result of connection is true, service host is n-devs-smb.tplinkcloud.com, port is 443.
omada-controller | 2020-12-01 18:46:13 [Thread-16] [INFO]-[SourceFile:114] - Close connection to SEF server.
omada-controller | 2020-12-01 18:46:13 [Thread-19] [INFO]-[SourceFile:403] - javax.net.ssl.SSLException: Socket closed
omada-controller | javax.net.ssl.SSLException: Socket closed
omada-controller |      at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1303) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:72) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:831) ~[?:1.8.0_275]
omada-controller |      at com.tplink.eap.cloudsdk.client.p.a(SourceFile:120) ~[cloudsdk-1.0.5.jar:?]
omada-controller |      at com.tplink.eap.cloudsdk.client.o.run(SourceFile:397) [cloudsdk-1.0.5.jar:?]
omada-controller |      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
omada-controller | Caused by: java.net.SocketException: Socket closed
omada-controller |      at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_275]
omada-controller |      at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_275]
omada-controller |      at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_275]
omada-controller |      at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1095) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:72) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:815) ~[?:1.8.0_275]
omada-controller |      ... 3 more
omada-controller | 2020-12-01 18:46:13 [Thread-19] [INFO]-[SourceFile:407] - ssl recv thread is stopped.
omada-controller | 2020-12-01 18:46:13 [Thread-16] [INFO]-[SourceFile:127] - Connect service server automatically, ConnectionType is PERSISTENT_CONNECTION.
omada-controller | 2020-12-01 18:46:14 [Thread-16] [INFO]-[SourceFile:366] - The result of connection is true.
omada-controller | 2020-12-01 18:46:25 [device-event-bus-0] [WARN]-[SourceFile:88] - Realtimeap is null, ap mac 74-DA-88-F9-D8-CF
omada-controller | 2020-12-01 18:46:26 [nioEventLoopGroup-9-1] [INFO]-[SourceFile:51] - success to send InitialSettingSync to 74-DA-88-F9-D8-CF
```

## This is the output of the openssl command you provided

```bash
root@omada:/cert# openssl x509 -in tls.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:35:f8:e2:88:af:a0:fc:31:f9:1e:7d:38:98:da:1a:bb:53
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Nov 25 23:06:44 2020 GMT
            Not After : Feb 23 23:06:44 2021 GMT
        Subject: CN = omada.iclick.tk
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:ce:77:4c:72:ea:1a:03:45:62:7d:98:40:cf:97:
                    7b:93:26:f5:a1:93:22:7b:9a:4c:a2:49:c8:d3:db:
                    c1:c9:81:73:34:ab:0c:67:a6:ba:ba:a0:f9:73:22:
                    6d:f9:17:19:8f:78:80:6a:42:81:1a:9b:e0:db:d7:
                    8a:5f:d5:ff:22:c8:ff:55:2e:d6:6b:c2:66:13:a6:
                    b8:55:40:9e:53:73:15:ae:8f:84:ee:d5:d2:16:cd:
                    29:72:88:2b:a3:3f:33:7e:9c:df:15:84:8b:3a:9f:
                    29:2d:85:27:c8:00:a4:1b:6d:27:60:2d:cb:c6:d7:
                    bb:37:bb:1d:e0:32:02:46:0c:52:9e:28:a1:75:d0:
                    48:bc:0b:6d:2c:0f:ce:2c:ca:65:9e:d3:f2:9e:a3:
                    97:5b:28:f4:44:8c:dc:50:6a:91:e2:87:2f:f6:f5:
                    0b:9f:93:0a:22:00:5b:f5:9e:2f:b4:60:3d:c0:8b:
                    08:5b:4d:51:78:d7:af:98:e3:fe:37:d8:3e:1f:e4:
                    5e:5e:04:26:e5:5b:e3:25:77:02:d0:b8:4d:30:db:
                    a0:de:53:16:72:9d:60:2a:aa:30:3d:8e:bc:cb:5b:
                    a4:58:db:45:14:0c:34:8e:62:2b:03:b5:a0:dd:13:
                    11:1f:a2:ff:aa:0e:1f:9d:c3:0e:1e:fb:e9:06:77:
                    78:e7
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                72:6D:97:E3:49:5F:41:32:08:8F:0F:29:DD:45:98:76:BB:D2:63:B4
            X509v3 Authority Key Identifier:
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access:
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name:
                DNS:omada.iclick.tk
            X509v3 Certificate Policies:
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            CT Precertificate SCTs:
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 44:94:65:2E:B0:EE:CE:AF:C4:40:07:D8:A8:FE:28:C0:
                                DA:E6:82:BE:D8:CB:31:B5:3F:D3:33:96:B5:B6:81:A8
                    Timestamp : Nov 26 00:06:44.330 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:30:A1:A9:EC:86:76:DE:47:F3:53:00:14:
                                E3:4E:DB:59:E3:A0:78:5D:5E:83:0B:A0:9F:F1:2A:EC:
                                DA:87:D5:4B:02:20:6B:75:90:27:42:24:A7:30:52:BA:
                                0C:03:1C:C1:41:26:41:30:9E:30:2E:73:92:74:11:A2:
                                C8:D0:95:A4:7B:66
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 7D:3E:F2:F8:8F:FF:88:55:68:24:C2:C0:CA:9E:52:89:
                                79:2B:C5:0E:78:09:7F:2E:6A:97:68:99:7E:22:F0:D7
                    Timestamp : Nov 26 00:06:44.342 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:26:94:EE:AA:8F:BD:0B:A5:98:A9:1B:CB:
                                13:72:9C:A8:CC:97:89:B8:EF:86:3C:42:E8:98:37:44:
                                89:3A:CD:A3:02:21:00:EB:A6:76:23:FC:9E:C3:A2:8C:
                                15:51:33:CE:D8:BF:62:64:6B:FD:35:FC:9E:DE:9A:9E:
                                42:A3:8F:81:52:80:0C
    Signature Algorithm: sha256WithRSAEncryption
         55:5a:6b:88:03:e9:71:64:8a:d1:6e:fc:ac:15:97:24:8b:0a:
         c0:1f:cb:34:70:94:4c:98:f1:a3:31:a1:a2:1e:b2:7a:47:09:
         e9:7f:9c:93:74:82:56:b8:4f:ca:cf:58:04:00:8a:c1:77:d3:
         3b:d9:a3:f7:c1:30:16:44:4d:77:cf:28:d6:90:2e:3b:29:de:
         c6:3d:f1:f8:6f:a9:6c:ff:58:bb:13:90:85:25:ce:d8:3c:7d:
         59:ac:f3:a5:06:e4:19:3b:73:9d:94:da:9b:ab:44:6a:85:55:
         fe:20:aa:6f:a7:40:b2:fe:ae:a2:bf:e9:97:7b:fa:19:bc:fa:
         86:05:0d:e2:bc:fc:55:65:30:ac:91:a7:b8:dd:30:21:6e:81:
         2f:1f:cc:d8:85:99:f1:56:16:49:49:32:cd:f5:5e:2c:14:b6:
         6a:37:f9:99:08:b0:cd:75:6a:b5:64:ad:f3:3f:47:11:b3:ec:
         c1:8e:bf:f8:3b:31:f8:d6:bf:c2:31:b5:d6:1d:db:38:07:8d:
         d8:c5:9d:13:e2:51:a1:93:0e:27:02:46:ae:5c:03:81:1d:57:
         30:bc:ed:d7:10:c7:68:0c:6c:5b:8f:2b:99:eb:65:db:a3:b7:
         8e:74:46:3e:25:9c:e3:20:69:8a:48:5f:10:e8:37:ba:b3:f4:
         0a:da:53:3e
```

**Comment by mbentley** [comment]
No worries - looks like you might have an older image as I don't see any messages about importing the cert.  Try to re-pull the image and try it again.

**Comment by ruslanguns** [comment]
Thanks for quick reply, I have modify the docker-compose file in order to use the latest image. Here is the logs 

```bash
root@omada:~/omada# docker-compose up -d && docker-compose logs -f
Pulling omada (mbentley/omada-controller:latest)...
latest: Pulling from mbentley/omada-controller
f22ccc0b8772: Pull complete
3cf8fb62ba5f: Pull complete
e80c964ece6a: Pull complete
60739ce57848: Pull complete
b7f256e7ce76: Pull complete
Digest: sha256:6a38816b1b29ffaafb4bff348f7006b14c2fdbfb3418cca1c04f63e99ec2ed46
Status: Downloaded newer image for mbentley/omada-controller:latest
Creating omada-controller ... done
Attaching to omada-controller
omada-controller | INFO: Time zone set to 'Etc/UTC'
omada-controller | INFO: Starting Omada Controller as user omada
omada-controller | 2020-12-01 19:09:56 [log4j-thread] [INFO]-[SourceFile:29] - success to load configuration omada.properties
omada-controller | 2020-12-01 19:09:56 [main] [INFO]-[SourceFile:89] - going to start local mongod.
omada-controller | 2020-12-01 19:09:58 [main] [INFO]-[SourceFile:167] - mongodb process id is 29
omada-controller | 2020-12-01 19:09:58 [main] [INFO]-[SourceFile:148] - Mongo DB server started
omada-controller | 2020-12-01 19:09:59 [main] [WARN]-[AbstractConnector.java:205] - Acceptors should be <= availableProcessors: ServerConnector@30f842ca{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
omada-controller | 2020-12-01 19:09:59 [main] [WARN]-[AbstractConnector.java:205] - Acceptors should be <= availableProcessors: ServerConnector@169bb4dd{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
omada-controller | 2020-12-01 19:10:29 [main] [INFO]-[SourceFile:35] - monitor context initialing...
omada-controller | 2020-12-01 19:10:34 [main] [INFO]-[SourceFile:290] - restart all customize tasks.
omada-controller | 2020-12-01 19:10:37 [main] [INFO]-[SourceFile:126] - no need to compatible db.
omada-controller | 2020-12-01 19:10:37 [main] [INFO]-[SourceFile:20] - Omada Controller started
omada-controller | 2020-12-01 19:10:37 [device-discovery-server] [INFO]-[SourceFile:54] - Start device discovery server
omada-controller | 2020-12-01 19:10:37 [device-manage-server] [INFO]-[SourceFile:111] - Start device manage server
omada-controller | 2020-12-01 19:10:37 [device-adopt-server] [INFO]-[SourceFile:82] - Start device adopt server
omada-controller | 2020-12-01 19:10:40 [Thread-11] [INFO]-[SourceFile:100] - CloudClient is started.
omada-controller | 2020-12-01 19:10:40 [Thread-11] [INFO]-[SourceFile:110] - Connect SEF server automatically.
omada-controller | 2020-12-01 19:10:40 [comm-pool-3] [INFO]-[SourceFile:84] - Starting PF module.
omada-controller | 2020-12-01 19:10:40 [comm-pool-3] [INFO]-[SourceFile:146] - Starting SCMP Server.
omada-controller | 2020-12-01 19:10:40 [comm-pool-3] [INFO]-[SourceFile:120] - Cloud service is started.
omada-controller | 2020-12-01 19:10:41 [Thread-11] [INFO]-[SourceFile:194] - The result of connection is true, service host is n-devs-smb.tplinkcloud.com, port is 443.
omada-controller | 2020-12-01 19:10:41 [Thread-11] [INFO]-[SourceFile:114] - Close connection to SEF server.
omada-controller | 2020-12-01 19:10:41 [Thread-14] [INFO]-[SourceFile:403] - javax.net.ssl.SSLException: Socket closed
omada-controller | javax.net.ssl.SSLException: Socket closed
omada-controller |      at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.TransportContext.fatal(TransportContext.java:324) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.TransportContext.fatal(TransportContext.java:267) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.TransportContext.fatal(TransportContext.java:262) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1303) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.access$300(SSLSocketImpl.java:72) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:831) ~[?:1.8.0_275]
omada-controller |      at com.tplink.eap.cloudsdk.client.p.a(SourceFile:120) ~[cloudsdk-1.0.5.jar:?]
omada-controller |      at com.tplink.eap.cloudsdk.client.o.run(SourceFile:397) [cloudsdk-1.0.5.jar:?]
omada-controller |      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
omada-controller | Caused by: java.net.SocketException: Socket closed
omada-controller |      at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_275]
omada-controller |      at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_275]
omada-controller |      at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_275]
omada-controller |      at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:457) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1095) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl.access$200(SSLSocketImpl.java:72) ~[?:1.8.0_275]
omada-controller |      at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:815) ~[?:1.8.0_275]
omada-controller |      ... 3 more
omada-controller | 2020-12-01 19:10:41 [Thread-14] [INFO]-[SourceFile:407] - ssl recv thread is stopped.
omada-controller | 2020-12-01 19:10:41 [Thread-11] [INFO]-[SourceFile:127] - Connect service server automatically, ConnectionType is PERSISTENT_CONNECTION.
omada-controller | 2020-12-01 19:10:42 [Thread-11] [INFO]-[SourceFile:366] - The result of connection is true.
omada-controller | 2020-12-01 19:10:53 [device-event-bus-0] [WARN]-[SourceFile:88] - Realtimeap is null, ap mac 74-DA-88-F9-D8-CF
omada-controller | 2020-12-01 19:10:54 [nioEventLoopGroup-9-1] [INFO]-[SourceFile:51] - success to send InitialSettingSync to 74-DA-88-F9-D8-CF
omada-controller | 2020-12-01 19:11:07 [scheduled-pool-8] [INFO]-[SourceFile:122] - Start checking last firmwares of managed devices.
omada-controller | 2020-12-01 19:11:07 [scheduled-pool-8] [INFO]-[SourceFile:132] - Checking last firmwares of managed devices succeed.

**Comment by mbentley** [comment]
Ah ok.  Interesting.  It seems like it isn't finding the files or that if statement isn't working.  Could you try to swap in this image which I added some debugging to?: `mbentley/omada-controller:4.2-test`


Example output:

```
INFO: Time zone set to 'Etc/UTC'
===============
START DEBUGGING
===============
+ set +e
+ ls -l /cert
total 8
-rw-r--r-- 1 root root 3579 Oct 30 00:16 tls.crt
-rw-r--r-- 1 root root 1679 Jan 10  2020 tls.key
+ grep -E Subject:|Issuer:
+ openssl x509 -in /cert/tls.crt -text -noout
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Subject: CN = ucp.test.demo.dckr.org
+ [ -f /cert/tls.key ]
+ [ -f /cert/tls.crt ]
+ echo INFO: Importing Cert from /cert/tls.[key|crt]
INFO: Importing Cert from /cert/tls.[key|crt]
+ openssl pkcs12 -export -inkey /cert/tls.key -in /cert/tls.crt -certfile /cert/tls.crt -name eap -out /opt/tplink/EAPController/keystore/cert.p12 -passout pass:tplink
+ rm /opt/tplink/EAPController/keystore/eap.keystore
+ keytool -importkeystore -deststorepass tplink -destkeystore /opt/tplink/EAPController/keystore/eap.keystore -srckeystore /opt/tplink/EAPController/keystore/cert.p12 -srcstoretype
PKCS12 -srcstorepass tplink
Importing keystore /opt/tplink/EAPController/keystore/cert.p12 to /opt/tplink/EAPController/keystore/eap.keystore...
Entry for alias eap successfully imported.
Import command completed:  1 entries successfully imported, 0 entries failed or cancelled

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /opt/tplink/EAPCo
ntroller/keystore/eap.keystore -destkeystore /opt/tplink/EAPController/keystore/eap.keystore -deststoretype pkcs12".
+ set +x
=============
END DEBUGGING
=============
...
```

**Comment by ruslanguns** [comment]
Again, sorry for late, Github does not notify me when new reply is there. I will have to find some external plugin at chrome to do it. Really I apologies.

![image](https://user-images.githubusercontent.com/19806968/100793522-22a28a80-3414-11eb-81f1-5e0dd827adba.png)

**Comment by mbentley** [comment]
Ah, it's a compose issue.

Remove the quotes around these values:
![screenshot 2020-12-01 at 3 34 14 PM](https://user-images.githubusercontent.com/414445/100793865-c8d99a80-33ea-11eb-9864-efa524879d23.png)

**Comment by ruslanguns** [comment]
Seems like it is working now.. but please see the output

![image](https://user-images.githubusercontent.com/19806968/100794067-f8050180-3414-11eb-9be4-4c8270111d07.png)

**Comment by mbentley** [comment]
There we go!  Yup, working now.

**Comment by ruslanguns** [comment]
Thank you so much! YTB 😎
